### ISSUE TITLE
Unable to run sbt app: java.lang.UnsupportedOperationException: empty.head

### ISSUE THREAD

**Issue by alelk** [kamon-io/sbt-kanela-runner#2]
I have the following issue when I'm performing `sbt run`:

```
[error] java.lang.UnsupportedOperationException: empty.head
[error] 	at scala.collection.immutable.Vector.head(Vector.scala:185)
[error] 	at kamon.instrumentation.sbt.SbtKanelaRunner$.$anonfun$findKanelaAgentJar$1(SbtKanelaRunner.scala:60)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (kanelaAgentJar) java.lang.UnsupportedOperationException: empty.head
```

I use SBT v 1.2.8, Scala 2.12.9.

My `project/plugins.sbt` file:

```
resolvers += Resolver.bintrayRepo("kamon-io", "sbt-plugins")
addSbtPlugin("io.kamon" % "sbt-kanela-runner" % "2.0.1")
```
Kamon dependencies I use:

```
 Seq(
    "io.kamon" %% "kamon-core" % "2.0.0",
    "io.kamon" %% "kamon-status-page" % "2.0.0",
    "io.kamon" %% "kamon-prometheus" % "2.0.0",
    "io.kamon" %% "kamon-zipkin" % "2.0.0",
    "io.kamon" %% "kamon-scala-future" % "2.0.0")
```

**Comment by ivantopo** [comment]
Hey @alelk, I'm closing this one because I'm almost sure this must be fixed in the most recent versions. Thanks for reporting and sorry the the super late response! Please re-open if you see this error again.
