### ISSUE TITLE
[error] java.lang.NoClassDefFoundError: sbt/ClassLoaderLayeringStrategy after adding kanela plugin in play project

### ISSUE THREAD

**Issue by Kalyan-M** [kamon-io/sbt-kanela-runner#5]
As the title says, when I'm trying to build my project after adding kanela runner to my plugins.sbt, I get `[error] java.lang.NoClassDefFoundError: sbt/ClassLoaderLayeringStrategy`. It works fine if I remove the dependency.
Below is the stacktrace:
```
[error] java.lang.NoClassDefFoundError: sbt/ClassLoaderLayeringStrategy
[error] 	at java.lang.Class.getDeclaredMethods0(Native Method)
[error] 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
[error] 	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
[error] 	at java.lang.Class.getMethod0(Class.java:3018)
[error] 	at java.lang.Class.getMethod(Class.java:1784)
[error] 	at org.jetbrains.sbt.extractors.UtilityTasks$.reflMethod$Method3(UtilityTasks.scala:145)
[error] 	at org.jetbrains.sbt.extractors.UtilityTasks$.$anonfun$areNecessaryPluginsLoaded$1(UtilityTasks.scala:145)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
[error] 	at scala.collection.immutable.List.foreach(List.scala:388)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:233)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
[error] 	at scala.collection.immutable.List.map(List.scala:294)
[error] 	at org.jetbrains.sbt.extractors.UtilityTasks$.areNecessaryPluginsLoaded(UtilityTasks.scala:145)
[error] 	at org.jetbrains.sbt.extractors.UtilityTasks$.$anonfun$acceptedProjects$4(UtilityTasks.scala:51)
[error] 	at org.jetbrains.sbt.extractors.UtilityTasks$.$anonfun$acceptedProjects$4$adapted(UtilityTasks.scala:51)
[error] 	at scala.Option.exists(Option.scala:240)
[error] 	at org.jetbrains.sbt.extractors.UtilityTasks$.$anonfun$acceptedProjects$2(UtilityTasks.scala:51)
[error] 	at org.jetbrains.sbt.extractors.UtilityTasks$.$anonfun$acceptedProjects$2$adapted(UtilityTasks.scala:50)
[error] 	at scala.collection.TraversableLike.$anonfun$filterImpl$1(TraversableLike.scala:247)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:937)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:937)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:70)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error] 	at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:246)
[error] 	at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:244)
[error] 	at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:104)
[error] 	at scala.collection.TraversableLike.filter(TraversableLike.scala:258)
[error] 	at scala.collection.TraversableLike.filter$(TraversableLike.scala:258)
[error] 	at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
[error] 	at org.jetbrains.sbt.extractors.UtilityTasks$.$anonfun$acceptedProjects$1(UtilityTasks.scala:50)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.lang.ClassNotFoundException: sbt.ClassLoaderLayeringStrategy
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[error] 	at java.lang.Class.getDeclaredMethods0(Native Method)
[error] 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
[error] 	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
[error] 	at java.lang.Class.getMethod0(Class.java:3018)
[error] 	at java.lang.Class.getMethod(Class.java:1784)
[error] 	at org.jetbrains.sbt.extractors.UtilityTasks$.reflMethod$Method3(UtilityTasks.scala:145)
[error] 	at org.jetbrains.sbt.extractors.UtilityTasks$.$anonfun$areNecessaryPluginsLoaded$1(UtilityTasks.scala:145)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
[error] 	at scala.collection.immutable.List.foreach(List.scala:388)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:233)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
[error] 	at scala.collection.immutable.List.map(List.scala:294)
[error] 	at org.jetbrains.sbt.extractors.UtilityTasks$.areNecessaryPluginsLoaded(UtilityTasks.scala:145)
[error] 	at org.jetbrains.sbt.extractors.UtilityTasks$.$anonfun$acceptedProjects$4(UtilityTasks.scala:51)
[error] 	at org.jetbrains.sbt.extractors.UtilityTasks$.$anonfun$acceptedProjects$4$adapted(UtilityTasks.scala:51)
[error] 	at scala.Option.exists(Option.scala:240)
[error] 	at org.jetbrains.sbt.extractors.UtilityTasks$.$anonfun$acceptedProjects$2(UtilityTasks.scala:51)
[error] 	at org.jetbrains.sbt.extractors.UtilityTasks$.$anonfun$acceptedProjects$2$adapted(UtilityTasks.scala:50)
[error] 	at scala.collection.TraversableLike.$anonfun$filterImpl$1(TraversableLike.scala:247)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:937)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:937)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:70)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error] 	at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:246)
[error] 	at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:244)
[error] 	at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:104)
[error] 	at scala.collection.TraversableLike.filter(TraversableLike.scala:258)
[error] 	at scala.collection.TraversableLike.filter$(TraversableLike.scala:258)
[error] 	at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
[error] 	at org.jetbrains.sbt.extractors.UtilityTasks$.$anonfun$acceptedProjects$1(UtilityTasks.scala:50)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by seansabour** [comment]
@Kalyan-M Were you able to resolve this issue, i'm running into the same exact problem with Play 2.7 with sbt version 1.2.8

**Comment by kgupta26** [comment]
I am also getting this error.. @Kalyan-M were you able to solve it?

**Comment by maayan-samari** [comment]
getting this error as well, has anyone solved it?

**Comment by jorkzijlstra** [comment]
Updating sbt to a newer version than `1.2.8` seems to have done the trick for me.
