### ISSUE TITLE
Errors when running with Java 15

### ISSUE THREAD

**Issue by honzabazant** [kamon-io/sbt-kanela-runner#8]
I found that sbt-kanela-runner does not work with Java 15.
What I have:
- plugins.sbt:
```
addSbtPlugin("io.kamon" % "sbt-kanela-runner" % "2.0.6")
```
- build.sbt:
```
import Dependencies._

val commonSettings = Seq(organization := "com.whatever", scalaVersion := "2.13.4", scalacOptions ++= Seq("-deprecation", "-feature"))
inThisBuild(commonSettings)

lazy val `app` =
  (project in file("app")).settings(
    libraryDependencies ++= Seq(akkaTyped, kamonBundle, logback, scalaLogging),
    Compile / mainClass := Some("com.whatever.app.App"),
    run / fork := true,
    run / javaOptions += "-Xmx8G"
  )
```
- Dependencies.scala:
```
import Versions._
import sbt._

case object Versions {
  val akkaVersion = "2.6.10"
  val kamonVersion = "2.1.9"
  val logbackVersion = "1.2.3"
  val scalaLoggingVersion = "3.9.2"
}

case object Dependencies {
  val akkaTyped = "com.typesafe.akka" %% "akka-actor-typed" % akkaVersion
  val kamonBundle = "io.kamon" %% "kamon-bundle" % kamonVersion
  val logback = "ch.qos.logback" % "logback-classic" % logbackVersion
  val scalaLogging = "com.typesafe.scala-logging" %% "scala-logging" % scalaLoggingVersion
}
```
- App.scala:
```
package com.whatever.app

import akka.actor.typed.scaladsl.Behaviors
import akka.actor.typed.{ ActorSystem, Behavior }
import kamon.Kamon

object App {
  sealed trait Command

  def apply(): Behavior[Command] =
    Behaviors.setup { ctx =>
      ctx.log.info("Running")
      Behaviors.same
    }

  def main(args: Array[String]): Unit = {
    Kamon.init()
    ActorSystem(App(), "app")
  }
}
```
- OS: macOs 11.1

When I run with Java 11, there is no problem:
```
$ sbt app/run
[info] welcome to sbt 1.4.6 (Oracle Corporation Java 11.0.9)
[info] loading settings for project global-plugins from sbt-updates.sbt ...
[info] loading global plugins from /Users/honzabazant/.sbt/1.0/plugins
[info] loading settings for project kanela-test-build from plugins.sbt ...
[info] loading project definition from /Users/honzabazant/develop/app/be/kanela-test/project
[info] loading settings for project kanela-test from build.sbt,version.sbt ...
[info] set current project to kanela-test (in build file:/Users/honzabazant/develop/app/be/kanela-test/)
[info] running (fork) com.whatever.app.App 
[info]  _  __                _        ______
[info] | |/ /               | |       \ \ \ \
[info] | ' / __ _ _ __   ___| | __ _   \ \ \ \
[info] |  < / _` | '_ \ / _ \ |/ _` |   ) ) ) )
[info] | . \ (_| | | | |  __/ | (_| |  / / / /
[info] |_|\_\__,_|_| |_|\___|_|\__,_| /_/_/_/
[info]                               
[info] ==============================
[info] Running with Kanela, the Kamon Instrumentation Agent :: (v1.0.5)
[error] WARNING: An illegal reflective access operation has occurred
[error] WARNING: Illegal reflective access by kamon.instrumentation.executor.ExecutorInstrumentation$ (file:/Users/honzabazant/develop/app/be/kanela-test/target/bg-jobs/sbt_dc828e4f/target/4203d6a9/e1876e73/kamon-bundle_2.13-2.1.9.jar) to field java.util.concurrent.Executors$DelegatedExecutorService.e
[error] WARNING: Please consider reporting this to the maintainers of kamon.instrumentation.executor.ExecutorInstrumentation$
[error] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[error] WARNING: All illegal access operations will be denied in a future release
[info] 12:51:46.293 [app-akka.actor.default-dispatcher-3] INFO akka.event.slf4j.Slf4jLogger - Slf4jLogger started
[info] 12:51:46.391 [app-akka.actor.default-dispatcher-5] INFO com.whatever.app.App$ - Running
```

But running with Java 15 produces many errors "Unsupported class file major version 59", which indicates some problem with Java version. Commenting out the plugin mutes these errors.
```
$ sbt app/run
[info] welcome to sbt 1.4.6 (N/A Java 15.0.1)
[info] loading settings for project global-plugins from sbt-updates.sbt ...
[info] loading global plugins from /Users/honzabazant/.sbt/1.0/plugins
[info] loading settings for project kanela-test-build from plugins.sbt ...
[info] loading project definition from /Users/honzabazant/develop/app/be/kanela-test/project
[info] compiling 1 Scala source to /Users/honzabazant/develop/app/be/kanela-test/project/target/scala-2.12/sbt-1.0/classes ...
[info] loading settings for project kanela-test from build.sbt,version.sbt ...
[info] set current project to kanela-test (in build file:/Users/honzabazant/develop/app/be/kanela-test/)
[info] compiling 1 Scala source to /Users/honzabazant/develop/app/be/kanela-test/app/target/scala-2.13/classes ...
[info] running (fork) com.whatever.app.App
[error] OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
[info]  _  __                _        ______
[info] | |/ /               | |       \ \ \ \
[info] | ' / __ _ _ __   ___| | __ _   \ \ \ \
[info] |  < / _` | '_ \ / _ \ |/ _` |   ) ) ) )
[info] | . \ (_| | | | |  __/ | (_| |  / / / /
[info] |_|\_\__,_|_| |_|\___|_|\__,_| /_/_/_/
[info]
[info] ==============================
[info] Running with Kanela, the Kamon Instrumentation Agent :: (v1.0.5)
[info] [main] ERROR 2021-01-13 12:53:04  Logger : Error => scala.util.Success with message Unsupported class file major version 59. Class loader: jdk.internal.loader.ClassLoaders$AppClassLoader@73d16e93: java.lang.IllegalArgumentException: Unsupported class file major version 59
[info]  at kanela.agent.libs.net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:195)
[info]  at kanela.agent.libs.net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:176)
[info]  at kanela.agent.libs.net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:162)
[info]  at kanela.agent.libs.net.bytebuddy.utility.OpenedClassReader.of(OpenedClassReader.java:86)
[info]  at kanela.agent.libs.net.bytebuddy.pool.TypePool$Default.parse(TypePool.java:681)
[info]  at kanela.agent.libs.net.bytebuddy.pool.TypePool$Default.doDescribe(TypePool.java:667)
[info]  at kanela.agent.libs.net.bytebuddy.pool.TypePool$Default$WithLazyResolution.access$001(TypePool.java:747)
[info]  at kanela.agent.libs.net.bytebuddy.pool.TypePool$Default$WithLazyResolution.doResolve(TypePool.java:845)
[info]  at kanela.agent.libs.net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:914)
[info]  at kanela.agent.libs.net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getModifiers(TypeDescription.java:8122)
[info]  at kanela.agent.libs.net.bytebuddy.description.ModifierReviewable$AbstractBase.matchesMask(ModifierReviewable.java:618)
[info]  at kanela.agent.libs.net.bytebuddy.description.ModifierReviewable$AbstractBase.isPublic(ModifierReviewable.java:336)
[info]  at kanela.agent.libs.net.bytebuddy.description.type.TypeDescription$AbstractBase.isVisibleTo(TypeDescription.java:7631)
[info]  at kanela.agent.libs.net.bytebuddy.matcher.VisibilityMatcher.matches(VisibilityMatcher.java:48)
[info]  at kanela.agent.libs.net.bytebuddy.matcher.VisibilityMatcher.matches(VisibilityMatcher.java:27)
[info]  at kanela.agent.libs.net.bytebuddy.matcher.ErasureMatcher.matches(ErasureMatcher.java:50)
[info]  at kanela.agent.libs.net.bytebuddy.matcher.ErasureMatcher.matches(ErasureMatcher.java:29)
[info]  at kanela.agent.libs.net.bytebuddy.matcher.MethodReturnTypeMatcher.matches(MethodReturnTypeMatcher.java:48)
[info]  at kanela.agent.libs.net.bytebuddy.matcher.MethodReturnTypeMatcher.matches(MethodReturnTypeMatcher.java:27)
[info]  at kanela.agent.libs.net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:122)
[info]  at kanela.agent.libs.net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:122)
[info]  at kanela.agent.libs.net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:122)
[info]  at kanela.agent.libs.net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:481)
[info]  at kanela.agent.libs.net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder.make(RebaseDynamicTypeBuilder.java:218)
[info]  at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:10123)
[info]  at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10494)
[info]  at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10457)
[info]  at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1500(AgentBuilder.java:10223)
[info]  at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:10907)
[info]  at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:10845)
[info]  at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
[info]  at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10413)
[info]  at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$ByteBuddy$ModuleSupport.transform(Unknown Source)
[info]  at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
[info]  at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
[info]  at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[info]  at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
[info]  at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
[info]  at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:825)
[info]  at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:723)
[info]  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:646)
[info]  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:604)
[info]  at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
[info]  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[info]  at kamon.module.ModuleRegistry.$anonfun$readModuleSettings$1(ModuleRegistry.scala:250)
[info]  at scala.collection.StrictOptimizedIterableOps.map(StrictOptimizedIterableOps.scala:99)
[info]  at scala.collection.StrictOptimizedIterableOps.map$(StrictOptimizedIterableOps.scala:86)
[info]  at scala.collection.immutable.Map$Map4.map(Map.scala:506)
[info]  at kamon.module.ModuleRegistry.readModuleSettings(ModuleRegistry.scala:248)
[info]  at kamon.module.ModuleRegistry.load(ModuleRegistry.scala:86)
[info]  at kamon.ModuleLoading.loadModules(ModuleLoading.scala:66)
[info]  at kamon.ModuleLoading.loadModules$(ModuleLoading.scala:65)
[info]  at kamon.Kamon$.loadModules(Kamon.scala:19)
[info]  at kamon.Init.init(Init.scala:35)
[info]  at kamon.Init.init$(Init.scala:33)
[info]  at kamon.Kamon$.init(Kamon.scala:19)
[info]  at com.whatever.app.App$.main(App.scala:17)
[info]  at com.whatever.app.App.main(App.scala)
...
```

Full output is in the attached file as it is quite large.
[sbt-kanela-runner-java-15.log](https://github.com/kamon-io/sbt-kanela-runner/files/5808498/sbt-kanela-runner-java-15.log)

Another issue that the error messages are invisible in the terminal (due to the text being printed with white foreground I guess), I can see them only if I select the text - see attached screenshot. This is quite confusing, although I do not know which code actually prints the escape sequences (i.e. whether the sbt-kanela-plugin itself or Kanela library or Kamon).
![sbt-kanela-runner-invisible-error](https://user-images.githubusercontent.com/25003718/104450725-d618a600-55a0-11eb-9b44-8b6cd7bb74cb.png)

**Comment by ivantopo** [comment]
Thanks for sharing this @honzabazant! Please upgrade to version `2.0.9` and this should be solved. I tried it with Java `15.0.2` a minute ago and it worked, at least on the test project I have here. Please re-open if the problem persists!

**Comment by honzabazant** [comment]
It works with version 2.0.9, thanks for the fix.
